@startuml
namespace nn {
  class FFN {
    - {static} SEED: long {read-only}
    - rand: Random {read-only}
    + layerSizes: int[] {read-only}
    - W: double[][][] {final}
    - b: double[][] {final}
    - a: double[][] {final}
    - z: double[][] {final}
    - delta: double[][] {final}

    + FFN(layerSizes: int[], hiddenActivation: ActivationFunction, outputActivation: ActivationFunction, lossFunction: LossFunction)
    - initWeights(layerSizes: int[])
    - forward(input: double[]): ForwardReturn
    - backward(yTrue: double[], a: double[][], z: double[][]): double[][]
    + predictQ(state: double[]): double[]
    + train(trainer: FFNTrainer, state: double[], target: double[], learningRate: double)
    + save(filepath: String)
    + {static} load(filepath: String): FFN
    + equals(obj: Object): boolean
  }

  note right of FFN::z
  a, z & delta are temp local variables for forward and backward pass
  only because we want to avoid re-allocating memory on each pass
  DO NOT READ BACK VALUES FROM THESE ARRAYS
  end note

  record FFN::ForwardReturn {
    a: double[][]
    z: double[][]
  }
  hide "FFN::ForwardReturn" methods

  namespace trainer {
    interface FFNTrainer {
      + train(a: double[][], z: double[][], delta: double[][], b: double[][], W: double[][][], layerSizes: int[], learningRate: double)
    }

    class FFNTrainerSGD implements FFNTrainer {
      + train(a: double[][], z: double[][], delta: double[][], b: double[][], W: double[][][], layerSizes: int[], learningRate: double)
      - updateWeights(delta: double[][], a: double[][], b: double[][], W: double[][][], layerSizes: int[], learningRate: double)
    }

    class FFNTrainerMBGD implements FFNTrainer {
      - miniBatchSize: int {read-only}
      - miniBatchCounter: int = 0
      - gradW: double[][][] {final}
      - gradB: double[][] {final}
      - layerSizes: int[] {read-only}

      + FFNTrainerMBGD(layerSizes: int[], miniBatchSize: int)
      + train(a: double[][], z: double[][], delta: double[][], b: double[][], W: double[][][], layerSizes: int[], learningRate: double)
      - updateWeights(learningRate: double, b: double[][], W: double[][][], layerSizes: int[])
      - resetGradients(layerSizes: int[])
    }
  }

  namespace loss {
    abstract class LossFunction {
      + {abstract} gradient(prediction: double[], target: double[]): double[]
      + {abstract} loss(predictions: double[], labels: double[]): double
      + {abstract} equals(obj: Object): boolean
      + hashCode(): int
    }
  }

  namespace activation {
    abstract class ActivationFunction {
      + {abstract} activate(x: double): double
      + {abstract} activateDerivative(x: double): double
      + {abstract} equals(obj: Object): boolean
      + hashCode(): int
    }
  }

  FFN --> "1 hiddenActivation" activation.ActivationFunction
  FFN --> "1 outputActivation" activation.ActivationFunction
  FFN --> "1 lossFunction" loss.LossFunction
}

namespace uttt {
  namespace actor {
    abstract class Actor {
      - player : PLAYER {read-only}

      + Actor(player: PLAYER)
      + getPlayer(): PLAYER
      + {abstract} move(state: PLAYER[][], localBoardSel: int, playableActions: int[]): int
      + {abstract} chooseBoard(state: PLAYER[][], playableBoards: int[]): int
    }

    class NNActor extends Actor {
      - stateBoardSelectionMultiplier: int {read-only}
      - alpha: double {read-only}
      - gamma: double {read-only}
      - epsilon: double {read-only}
      - lastAction: Integer = null
      - oldState: double[] = null
      - oldLocalEndedStatus: ENDED_STATUS = null
      - eventHandlerRegistered: boolean = false

      + NNActor(player: PLAYER, net: FFN, trainer: FFNTrainer, alpha: double, gamma: double, epsilon: double)
      + move(state: PLAYER[][], localBoardSel: int, playableActions: int[]): int
      + chooseBoard(state: PLAYER[][], playableBoards: int[]): int
      - predict(state: double[], objects: int[]): int
      - train(state: double[], newState: double[], globalEndedStatus: ENDED_STATUS, action: int, playableActions: int[])
      + eventHandler(event: Observer.Event)
      - convertPlayerStateToCellState(state: PLAYER[][]): CELL_STATE[][]
      - convertCellStateToDoubleState(state: CELL_STATE[][]): double[]
      - getStateWithBoardSelection(state: CELL_STATE[][], localBoardSel: Integer): double[]
      - calculateReward(globalEndedStatus: ENDED_STATUS, localEndedStatus: ENDED_STATUS): int
    }

    class GUIActor extends Actor {
      - moveHandler: TriFunction<PLAYER[][], Integer, int[], Integer> {read-only}
      - chooseBoardHandler: BiFunction<PLAYER[][], int[], Integer> {read-only}

      + GUIActor(player: PLAYER, moveHandler: TriFunction<PLAYER[][], Integer, int[], Integer>, chooseBoardHandler: BiFunction<PLAYER[][], int[], Integer>)
      + move(state: PLAYER[][], localBoardSel: int, playableActions: int[]): int
      + chooseBoard(state: PLAYER[][], playableBoards: int[]): int
    }

    enum PLAYER {
      X
      O
    }
    hide PLAYER methods

    enum NNActor::CELL_STATE {
      YOU,
      ENEMY,
      NOT_SET
    }
    hide "NNActor::CELL_STATE" methods
  }

  namespace board {
    abstract class Board <T> {
        ~ board: T[3][3] {final}

        + Board(cls: Class<T>)
        + getCell(idx: int): T
        + {abstract} calculateEndedStatus(): ENDED_STATUS
    }

    class GlobalBoard extends Board {
      - board: LocalBoard[3][3] {final}

      + GlobalBoard()
      + getState(): PLAYER[][]
      + calculateEndedStatus(): ENDED_STATUS
      + getPlayableLocalBoards(): int[]
    }

    class LocalBoard extends Board {
        - board: PLAYER[3][3] {final}
        - idx: int {read-only}

        + LocalBoard(idx: int)
        + getIdx(): int
        + setCell(idx: int, player: PLAYER)
        + getState(): PLAYER[]
        + calculateEndedStatus(): ENDED_STATUS
        + getPlayableActions(): int[]
    }

    GlobalBoard --> "9 board[3][3]" LocalBoard

    exception CellAlreadySetException {
    }
    hide CellAlreadySetException members

    enum ENDED_STATUS {
      X,
      O,
      TIE
    }
    hide ENDED_STATUS methods
  }

  namespace observer {
    record Event {
      player: PLAYER
      board: int
      oldState: PLAYER[][]
      newState: PLAYER[][]
      globalEndedStatus: ENDED_STATUS
      localEndedStatus: ENDED_STATUS
    }
    hide Event Methods

    interface Observer <<Functional>> {
      + notify(event: Event)
    }
    hide Observer attributes
  }

  namespace storage {
    record Move {
      player: PLAYER
      board: int
      action: int
      localEndedStatus: ENDED_STATUS
      globalEndedStatus: ENDED_STATUS
    }
    hide Move methods

    class StorageManager() {
      - StorageManager()
      - {static} moveToMap(move: Move): Map<String, Object>
      - {static} mapToMove(map: Map<String, Object>): Move
      + {static} save(moves: Move[], filepath: String)
      + {static} load(filepath: String): Move[]
      - {static} <T> deeperClone(source: T[][]): T[][]
      - {static} applyMove(state: PLAYER[][], board: int, action: int, player: PLAYER)
      - {static} applyMove(state: PLAYER[][], move: Move)
      + {static} movesToState(moves: Move[]): PLAYER[][]
      + {static} movesToStates(moves: Move[]): PLAYER[][][]
    }

    class MoveHistoryGenerator {
      - List<Move> history {final}

      + MoveHistoryGenerator()
      + getHistory(): Move[]
      + handleEvent(event: Observer.Event)
    }
  }

  class Game {
    + Game(actorX: Actor, actorO: Actor, observers: Observer[])
    + Game(actorX: Actor, actorO: Actor)
    + run()
    - move(globalBoard: GlobalBoard, actor: Actor, desiredBoardIdx: int): int
    + addObserver(observer: Observer)
    + removeObserver(observer: Observer)
    - notifyObservers(...)
  }

  Game --> "1" GlobalBoard
  Game --> "1 actorX" Actor
  Game --> "1 actorO" Actor
  Game --> "*" Observer
}

uttt.actor.NNActor --> "1 trainer" nn.trainer.FFNTrainer
uttt.actor.NNActor --> "1 net" nn.FFN


namespace helper {
    class Stats {
      - o_wins: int = 0
      - x_wins: int = 0
      - ties: ties = 0

      + Stats()
      + logGameEnd(endedStatus: ENDED_STATUS)
      + {static} logEpisodeFinished(ep: int)
      + logAllEpisodesEnd(hiddenActivations: ActivationFunction)
      + boardToString(board: GlobalBoard, globalCellIndex: int, localCellIndex: int): String
      + boardToString(board: GlobalBoard): String
    }

    class Utils {
      + {static} ENDED_STATUS_TO_PLAYER: Map<ENDED_STATUS, PLAYER> {read-only}
      + {static} PLAYER_TO_ENDED_STATUS: Map<PLAYER, ENDED_STATUS> {read-only}
      + {static} activationToName: Map<ActivationFunction, String> {read-only}
      + {static} nameToActivation: Map<String, ActivationFunction> {read-only}
      + {static} lossToName: Map<LossFunction, String> {read-only}
      + {static} nameToLoss: Map<String, LossFunction> {read-only}
      - {static} wins: int[][] {read-only}

      - Utils()
      - {static} <T> ENDED_STATUS ended(T[], converter: Function<T, ENDED_STATUS>): ENDED_STATUS
      + {static} globalEnded(state: PLAYER[][]): ENDED_STATUS
      + {static} localEnded(state: PLAYER[]): ENDED_STATUS
    }
}
@enduml